return {
  -- Keep parser installs under nvim-data/site instead of relying on implicit defaults.
  install_dir = vim.fs.joinpath(vim.fn.stdpath "data", "site"),
  ensure_installed = {
    "lua",
    "vim",
    "vimdoc",
    "go",
    "gomod",
    "gowork",
    "gosum",
    "c_sharp",
    "css",
    "html",
    "razor",
    "rust",
    "python",
    "powershell",
    "toml",
    "json",
    "xml",
    "yaml",
    "bash",
    "markdown",
    "markdown_inline",
    "sql",
  },
  auto_install = true,
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
  },
}
