require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set

map("n", ";", ":", { desc = "CMD enter command mode" })
map("i", "jk", "<ESC>")

map("n", "<leader>lf", function()
  require("configs.dotnet").format_buffer()
end, { desc = "Format buffer" })
map("n", "<leader>lr", vim.lsp.buf.rename, { desc = "LSP rename" })
map("n", "<leader>la", vim.lsp.buf.code_action, { desc = "LSP code action" })
map("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
map("n", "gr", vim.lsp.buf.references, { desc = "References" })
map("n", "gi", vim.lsp.buf.implementation, { desc = "Implementation" })
map("n", "K", vim.lsp.buf.hover, { desc = "Hover" })
map("n", "<leader>li", function()
  local enabled = vim.lsp.inlay_hint.is_enabled()
  vim.lsp.inlay_hint.enable(not enabled)
end, { desc = "Toggle inlay hints" })

map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics" })
map("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", { desc = "Buffer diagnostics" })
map("n", "<leader>xq", "<cmd>Trouble qflist toggle<cr>", { desc = "Quickfix list" })
map("n", "<leader>xt", "<cmd>TodoTrouble<cr>", { desc = "Todo comments" })

map("n", "<F5>", "<cmd>lua require('dap').continue()<cr>", { desc = "Debug continue", silent = true })
map("n", "<F10>", "<cmd>lua require('dap').step_over()<cr>", { desc = "Debug step over", silent = true })
map("n", "<F11>", "<cmd>lua require('dap').step_into()<cr>", { desc = "Debug step into", silent = true })
map("n", "<F12>", "<cmd>lua require('dap').step_out()<cr>", { desc = "Debug step out", silent = true })
map("n", "<leader>db", "<cmd>lua require('dap').toggle_breakpoint()<cr>", { desc = "Toggle breakpoint", silent = true })
map("n", "<leader>du", "<cmd>lua require('dapui').toggle()<cr>", { desc = "Toggle debug UI", silent = true })

map("n", "<leader>tn", function()
  require("neotest").run.run()
end, { desc = "Run nearest test" })
map("n", "<leader>tf", function()
  require("neotest").run.run(vim.fn.expand "%")
end, { desc = "Run file tests" })
map("n", "<leader>tl", function()
  require("neotest").run.run_last()
end, { desc = "Run last test" })
map("n", "<leader>to", function()
  require("neotest").output_panel.toggle()
end, { desc = "Toggle test output" })
map("n", "<leader>ts", function()
  require("neotest").summary.toggle()
end, { desc = "Toggle test summary" })

map("n", "<leader>gv", "<cmd>VenvSelect<cr>", { desc = "Select Python venv" })
map("n", "<leader>ggt", "<cmd>GoTestFile<cr>", { desc = "Go test file" })
map("n", "<leader>gga", "<cmd>GoAlt<cr>", { desc = "Go alternate file" })
map("n", "<leader>nb", "<cmd>Dotnet build<cr>", { desc = ".NET build" })
map("n", "<leader>nr", "<cmd>Dotnet run default<cr>", { desc = ".NET run default" })
map("n", "<leader>nt", "<cmd>Dotnet test<cr>", { desc = ".NET test" })
map("n", "<leader>nT", "<cmd>Dotnet testrunner<cr>", { desc = ".NET test runner" })
map("n", "<leader>np", "<cmd>Dotnet project view<cr>", { desc = ".NET project view" })
map("n", "<leader>no", "<cmd>Dotnet outdated<cr>", { desc = ".NET outdated packages" })
map("n", "<leader>ns", "<cmd>Dotnet secrets<cr>", { desc = ".NET secrets" })
map("n", "<leader>nd", "<cmd>Dotnet diagnostic<cr>", { desc = ".NET workspace diagnostics" })
map("n", "<leader>rr", function()
  vim.cmd.RustLsp "runnables"
end, { desc = "Rust runnables" })
